export const skillsData = [
    { name: "TypeScript", tech: "Programming Language" },
    { name: "JavaScript", tech: "Programming Language" },
    { name: "C++", tech: "Programming Language" },
    { name: "Java", tech: "Programming Language" },
    { name: "React", tech: "Frontend" },
    { name: "Flutter", tech: "Frontend" },
    { name: "Android", tech: "Frontend" },
    { name: "HTML5", tech: "Frontend" },
    { name: "CSS3", tech: "Frontend" },
    { name: "Redux", tech: "Frontend" },
    { name: "Next.js", tech: "Frontend" },
    { name: "Node.js", tech: "Backend" },
    { name: "Express", tech: "Backend" },
    { name: "Prisma", tech: "Backend" },
    { name: "AWS", tech: "Backend" },
    { name: "PostgreSQL", tech: "Database" },
    { name: "Firebase", tech: "Backend" },
    { name: "MongoDB", tech: "Database" },
    { name: "SQL", tech: "Database" },
    { name: "Docker", tech: "Others" },
    { name: "Vercel", tech: "Others" },
    { name: "Jest", tech: "Others" },
    { name: "Cypress", tech: "Others" },
    { name: "Git", tech: "Others" },
    { name: "GitHub", tech: "Others" },
    { name: "GitLab", tech: "Others" },
    { name: "Jira", tech: "Others" },
    { name: "Visual Studio Code", tech: "Others" },
    { name: "Android Studio", tech: "Others" },
    { name: "Linux", tech: "Others" }
];
